### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/hacktoberfest-cwb-2018#1]
Dia 20/10
- 09h30: Abertura
- 10:00: Introdução à Software aberto e livre
- 11h00: Apresentação de Projetos
- 14h00: Workshops
- 16h00: Período de colaboração não estruturada
- 18h30: Fechamento
- 19h00: Happy Hour

**Comment by almeidaraul** [comment]
Encerrando as inscrições com 41 inscritos. Podemos conversar amanhã de manhã sobre paralelização do evento?

**Comment by abelsiqueira** [comment]
Sim, amanhã estarei na minha sala de manhã.
