### ISSUE TITLE
Data limite de inscrição

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/hacktoberfest-cwb-2018#10]
Eu preciso passar os inscritos para o Setor e o @haltsimog para o DINF, então vou colocar a data limite de inscrição para **16/10 até 23:59**.

Sugestões, por favor avisem.

**Comment by chunggnuhc** [comment]
@haltsimog eu sei que o prazo de inscrições já acabou, mas semana passada eu acabei comentando sobre o evento para um aluno meu e ele se interessou e eu nao mandei o site para ele. Tem como adicionar só mais um aluno?
