### ISSUE TITLE
Material Gráfico

### ISSUE THREAD

**Issue by gustavosarturi** [abelsiqueira/hacktoberfest-cwb-2018#11]
Olá! Eu acredito que não possuo permissões para colocar as imagens diretamente aqui neste repositório, e levando em consideração que sou um Jovem Padawan no Github, <a href="https://mega.nz/#F!9foHSSgZ!IFMaoA8srzSX5fXlsRYHgQ" target="_blank">clique aqui</a> para fazer o download do material gráfico do evento em Curitiba. Qualquer modificação, sugestão, contacte-me.

<center><img src="https://imgur.com/mIA6rnX.png"/></center>

**Comment by abelsiqueira** [comment]
Adicionadas [aqui](https://github.com/hacktoberfestcwb/2018/tree/master/art), obrigado Gustavo.

**Comment by abelsiqueira** [comment]
Gustavo, eu precisava desse `48 Copy 4` com resolução dobrada. Se ficar muito grande eu converto pra jpg, mas o tamanho que eu estou usando no site é quase o dobro desse.

**Comment by gustavosarturi** [comment]
Copy that! Qualquer coisa me repassa o tamanho exato que eu reduzo caso precisar.

<a href="https://imgur.com/7FLe8P9" target="_blank">Link</a>
