### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by phls** [abelsiqueira/hacktoberfest-cwb-2018#14]
Olá pessoal, legal a iniciativa!

Não sei se vocês já viram isso, mas provavelmente vocês precisam ver com o C3SL fazer algum tipo de liberação pra nós de fora da UFPR (sou ex-aluno do BCC) usarmos a rede wifi lá.
Talvez criar uma conta de visitante, ou algo assim.

Abraços,

**Comment by abelsiqueira** [comment]
Olá Paulo, obrigado pela dica.
O @haltsimog é do PET e está verificando o que tem que fazer. A inscrição acaba cedo pra dar tempo de passarmos a lista pro DINF.

Abraço.
