### ISSUE TITLE
Atualizações do site

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/hacktoberfest-cwb-2018#16]
cc @GabrielTha

- [x] Dizer que as inscrições estão fechadas, e que a entrada no período da tarde é só pra quem se inscreveu, e que só quem se inscreveu pode usar a internet e os computadores;
- [x] Atualizar workshops;

**Comment by GabrielTha** [comment]
@abelsiqueira 

Feito: Informações de fechamento das inscrições e acesso ao local.
Com relação aos workshops, estou fechando a lista de todos os workshops e amanha atualizo.
Acabei dando um pull request somente para as informações que já fiz. Vc prefere que eu cancele esse pull request e faça um unico pull para as duas tarefas? Ou posso manter assim mesmo?

**Comment by abelsiqueira** [comment]
Gabriel, não recebi os pull requests. Será que você fez pro próprio fork?

**Comment by GabrielTha** [comment]
Corrigido. Acho que agora vai dar certo

**Comment by abelsiqueira** [comment]
Feito em #18 e #19.
