### ISSUE TITLE
Apresentações

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/hacktoberfest-cwb-2018#2]
- Abel Soares Siqueira
  - Julia e JuliaSmoothOptimizers

**Comment by almeidaraul** [comment]
Entrei em contato com o GruPy ontem e algumas pessoas tiveram interesse. Eles também estavam querendo organizar um hacktober, então agora nós temos esse apoio extra.  
Não tive resposta do C3SL ainda. Vou tentar encontrar alguém pessoalmente sexta-feira.
Só consegui me comunicar com o LEG por facebook, e ainda não responderam.

**Comment by abelsiqueira** [comment]
Que bom. Passou este link pra esse pessoal?

**Comment by almeidaraul** [comment]
Sim. Dentro do grupo, eles "alocaram a responsabilidade" da organização (na parte deles, em parceria conosco) para um menino que estuda na UFPR (acho que no botânico).

**Comment by almeidaraul** [comment]
C3SL confirmado.

**Comment by abelsiqueira** [comment]
Confirmado que vão falar alguma coisa? Quem? Independente do dia?

**Comment by abelsiqueira** [comment]
Pode preencher ali em cima?

**Comment by almeidaraul** [comment]
Fomos eu e o Vinicius lá no C3SL e parece que os projetos deles são de código aberto, sim (mas talvez seja complicado demais pra usar lá). Vão retornar pra nós pessoas pra apresentarem e, se existirem, pessoas com projetos pessoais de código aberto.

**Comment by d1l4y** [comment]
> Bom dia,
> 
> O Matheus Horstmann (mch15) poderá participar apresentando sobre o C3SL. 
> 
> Atenciosamente,
> Henrique Varella  Ehrenfried
> 

 --------Recebi esse email do Henrique do C3SL--------

**Comment by horstmannmat** [comment]
Oi, eu vou apresentar sobre o c3sl :) 
Me pediram pra fazer uma apresentação da diferença entre open-source e free-software também.
