### ISSUE TITLE
Divulgação

### ISSUE THREAD

**Issue by almeidaraul** [abelsiqueira/hacktoberfest-cwb-2018#3]
- [x] Deixar tudo da divulgação pronto  
Pedir divulgação para:  
- [x] CAAD (CA de BCC)  
- [x] CEIB (IBM)  
- [x] PET matemática - UFPR  
- [x] PET estatística - UFPR  
- [x] PETECO (engenharia da computação - UTFPR)  
- [x] CASI (Sistemas de Informação - PUC)  
- [x] CACCo (ciência da computação - PUC)

**Comment by chunggnuhc** [comment]
Eu tenho um contato do professor do departamento de Informática e comentei inicialmente sobre o evento. Já mandei um email confirmando o interesse dele e do contato do PETECO e de outros possíveis interessados.

**Comment by almeidaraul** [comment]
Legal! Qual professor?

**Comment by chunggnuhc** [comment]
O prof Luis Augusto Pelisson, mas ainda nao tive resposta. Se vc conhecer outro professor, seria interessante conversar.

**Comment by chunggnuhc** [comment]
Bem, entrei em contato com a profa Leyza Dorini que já entrou em contato com o PETECO. O PETECO já foi informado do nosso evento e agora é só aguardar a resposta deles.

**Comment by almeidaraul** [comment]
Divulgação iniciada. Criei formulário pra inscrição e publiquei um evento no facebook do PET Computação. Também publiquei coisa no Instagram do grupo. Agora vou atrás do GruPy e de outros PET/CAs

**Comment by abelsiqueira** [comment]
Alguém mandou mensagem pro CACCo?

**Comment by abelsiqueira** [comment]
@HektorDannyel, você pode mandar anunciar pro PET Estatística?
