### ISSUE TITLE
Local e data

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/hacktoberfest-cwb-2018#4]
cc @haltsimog

Possibilidades, prós e contras

- 12 de Outubro - algum lugar na UFPR
  - Prós: Feriado todo mundo tem livre;
  - Contra: Muito próximo; ~~entrada restrita~~

- 13 de Outubro - algum lugar na UFPR
  - Prós: Depois do feriado, é pra ter livre também;
  - Contra: Muito próximo; ~~entrada restrita (na UFPR é recesso, vai estar tão fechado quanto)~~

- 20 de Outubro
  - Prós: Tempo suficiente
  - Contra: Na UFPR vai ter vestibular dia 21, então dia 20 deve estar sem acesso;

- ~~27 de Outubro~~ Segundo turno das eleições, prov.
  - ~~Prós: Muito tempo pra preparar~~
  - ~~Contra: Muito tarde;~~

- Algum horário na semana de 22 a 26 (Sem. Acad.)
  - Prós: Terá bastante adesão de alunos;
  - Contra: Não seria muito tempo; não terá muito gente de fora.

**Comment by almeidaraul** [comment]
Em entrada restrita você se refere aos departamentos?

**Comment by abelsiqueira** [comment]
Entrada restrita na própria UFPR. No sábado a entrada é permitida até umas 13h-14h, e no domingo não é permitida. Nos dias de semana não feriado entre umas 6h e 23h mais ou menos.

**Comment by almeidaraul** [comment]
No SulPET que rolou esse ano eles deixavam uma entrada "nos fundos" aberta - aquela no caminho do SEPT, mas não sei se foi exclusivamente pra os eventos que aconteceram. Se for esse o caso podemos pedir.

**Comment by almeidaraul** [comment]
Se o que eu comentei ainda funcionar, o problema que sobra é abrir laboratório ou sala com wifi.

**Comment by abelsiqueira** [comment]
No dia 28/10 será o segundo turno das eleições, então dia 27 deve ser impossível de usar também.

Por outro lado, verifiquei que podemos abrir deixar o acesso livre para as pessoas que foram participar, desde de que elas deixem os dados. Ainda não vi com que antecedência.

**Comment by almeidaraul** [comment]
Deixem os dados onde? Dá pra fazer uma inscrição de Google forms e, no dia, dar etiquetas com nome (manuscrito mesmo) pra as pessoas.

**Comment by abelsiqueira** [comment]
Que deixem os dados pra eu passar pra secretaria do setor.

Vamos fechar o dia então? Seria bom se tivesse alguma informação das pessoas de fora se eles tem interesse em fazer num local que não seja a UFPR, porque na UFPR só podemos dias 12 ou 13, a priori.

**Comment by almeidaraul** [comment]
Ainda estou aguardando resposta do pessoal.

**Comment by abelsiqueira** [comment]
Acabei de conversar com o Gustavo e o Raul, e fui avisado que podemos fazer dia 20 no DINF, e que pra eles é melhor dia 20, então fechamos dia 20.

**Comment by gustavosarturi** [comment]
Certo! Acabei de fazer o download do pacote de mídia do Hacktober no site deles para editar, assim que eu puder, ainda hoje, farei os banners e enviarei a vocês;
