### ISSUE TITLE
Projetos

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/hacktoberfest-cwb-2018#5]
Colocar aqui links de projetos para trabalhar.

- [Projetos brasileiros para contribuir](https://medium.com/@jessicatemporal/projetos-brasileiros-para-contribuir-nesse-hacktoberfest-vers%C3%A3o-2018-4925959b9411) (coletado por @jtemporal)
- [Tradução do Julia-Cheat-Sheet](https://github.com/JuliaDocs/Julia-Cheat-Sheet); estou organizando [aqui](https://github.com/abelsiqueira/Julia-Cheat-Sheet-pt-br);
- [mcglm - Fitting multivariate covariance generalized linear models](https://github.com/wbonat/mcglm);
- [mglm4twin - Multivariate Generalized Linear models for twin data](https://github.com/wbonat/mglm4twin);
- [labestData - Conjuntos de dados](https://github.com/pet-estatistica/labestData)
- [nlmSet - Catálogo Web de Modelos Não Lineares](https://github.com/leg-ufpr/nlmSet)

**Comment by d1l4y** [comment]
Oi Vinicius,

Eu tenho dois projeto em R que são abertos e poderiam receber colaboração.
Eu não sei se são adequados para apresentar no evento.
Você pode dar uma olhada no github 

O mcglm é um pacote oficial do R e encontra-se estável. Porém, tem muitas melhorias que podem ser feitas.

[https://github.com/wbonat/mcglm](https://github.com/wbonat/mcglm)

O mglm4twin é um projeto novo que ainda tem muito o que fazer

[https://github.com/wbonat/mglm4twin](https://github.com/wbonat/mglm4twin)

Os dois são relacionados a modelos estatísticos multivariados.

Se achar que isso é relevante eu posso apresentar. Só me mande as instruções gerais, dia, hora e duração e uma idéia da platéia.

**--------------- Email que recebi do Wagner Bonat (integrante do LEG UFPR) ---------------**

**Comment by abelsiqueira** [comment]
Guia para mantenedores/supervisores de projetos:
- O Hacktoberfest é um evento de divulgação do Software Open Source, feito pela Digital Ocean em colaboração com o GitHub e Twilio;
- A ideia é apresentar para iniciantes o que é OSS, GitHub, e colaboração em software;
- A ideia também é angariar contribuidores, experientes ou não, para trabalhar em projetos OS;
- As regras são: fazer cinco pull requests no **GitHub** para projetos open source;
- Para seu projeto, considere abrir **issues**, de preferência indicando quando forem bons para iniciantes com labels (e.g. **good first-pr**);
  - Alguns exemplos de issues fáceis: corrigir/traduzir documentação, buscar erros de digitação;
  - Exemplos médios: melhorar/escrever documentação, criar mais testes;
- Sua apresentação é de 5-10 minutos, tente fazê-la para um público completamente leigo;
  - Para que serve seu software?
  - Qual a importância dele (pra você ou pra sociedade)?;
  - Qual o usuário tradicional?
  - Quais ferramentas são requeridas para uma contribuição substancial?
- Após a apresentação teremos um período de colaboração não estruturada, onde pessoas interessadas podem te buscar para discutir o que podem fazer para ajudar, ou pedir ajuda em coisas específicas do seu código;
- Mantenha em mente os **valores do Hacktoberfest**:
  - Todos são bem-vindos;
  - Quantidade é legal, qualidade é essencial;
  - Ações de curto prazo, impacto de longo prazo.

**Comment by abelsiqueira** [comment]
Pessoal, coloquei um pequeno guia acima para ajudar na hora de buscar pessoas para participar. Por favor, agreguem perguntas por aqui, para criarmos um breve FAQ.

**Comment by abelsiqueira** [comment]
@wbonat, obrigado pelo interesse e disponibilidade. Coloquei uma pequena lista de informações para mantenedores, onde você pode ver melhor o que planejamos no evento.
Respondendo suas perguntas,

> Se achar que isso é relevante eu posso apresentar.

Sendo um projeto open source, é relevante. Sobre ser especificamente relevante pelo assunto, pode não ser pra todos, mas também não é necessário. Esperamos ter alguns alunos da estatística, mas se você tiver issues simples, outras pessoas podem ajudar também.

> Só me mande as instruções gerais, dia, hora e duração e uma idéia da platéia.

Dia 20 de Outubro, agenda ainda está sendo definida, mas o evento deve começar umas 9h30-10h00. Se você puder, e achar que vale a pena, teremos um período livre para colaborações, onde você pode direcionar os interessados em lhe ajudar. A duração da apresentação seria de uns 5-10 minutos, pois é só pra jogar o anzol. Palavras do hacktoberfest: (*3–5 minute demos by anyone interested in sharing their open source projects*).
E o público geral seria bastante heterogêneo, mas você pode decidir focar só nos estatísticos da sala.

Se for do seu interesse participar, me confirme que eu adiciono sua apresentação na lista.

Abraço.

**Comment by abelsiqueira** [comment]
@sheilagomes, passando a conversa pra cá.

Sua participação é bem-vinda. Sobre apresentar algo, se você tiver algum projeto open source que queira contribuição, você pode falar sobre ele, uns 5 minutos basta, e aí os interessados durante o evento te procuram para discutir contribuições. Coloquei umas dicas ali em cima para você ver se é do seu interesse.

**Comment by sheilagomes** [comment]
Obrigada, @abelsiqueira , vou ler e qualquer coisa te aviso o mais brevemente possível.

**Comment by sheilagomes** [comment]
A vida complicou aqui, então vou participar só contribuindo mesmo, ok? Desculpe a demora da resposta. Nos vemos no sábado!

**Comment by abelsiqueira** [comment]
Sem problemas. Até sábado.

**Comment by almeidaraul** [comment]
Atualização que esqueci de dar: o PET vai levar alguns projetos. Normalmente usamos o gitlab do C3SL, mas certos projetos já estão no GitHub e vamos adicionar alguns para o evento.

**Comment by abelsiqueira** [comment]
Obrigado a todos aqueles que participaram, principalmente aqueles que também ajudaram na tradução do Cheat Sheet. Ainda tem alguns PRs sobrando, pra quem estiver buscando.

Também tem um PR pra remover do saiadecasa.github.io.

Quem tiver interesse, já crie o repositório para 2019. Devemos começar a organizar em abril, potencialmente.

Abraços.

![fechamento](https://user-images.githubusercontent.com/1068752/47323352-c6b08980-d631-11e8-84c5-3e45537addcc.jpg)
