### ISSUE TITLE
Colocar o evento de Curitiba no site do evento oficial

### ISSUE THREAD

**Issue by chunggnuhc** [abelsiqueira/hacktoberfest-cwb-2018#6]
https://docs.google.com/spreadsheets/d/1yjPG_WoF_6ZkrJF7pHZjAdr0ztt-23fNK9DFgNZvB80/edit#gid=0

**Comment by almeidaraul** [comment]
Precisamos decidir local e data (#4) antes, certo?

**Comment by abelsiqueira** [comment]
Sim

**Comment by almeidaraul** [comment]
Antes de preencher precisamos confirmar quantidade suportada de pessoas.

**Comment by abelsiqueira** [comment]
Isso você vai ver aí?

**Comment by almeidaraul** [comment]
O que coloco em "Format"?

**Comment by abelsiqueira** [comment]
Workshop

**Comment by almeidaraul** [comment]
(Coloquei lá)
