### ISSUE TITLE
Criar formulário de inscrição

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/hacktoberfest-cwb-2018#8]
Pedir
- Nome completo
- CPF (pra entrar aqui)
- Ferramentas conhecidas
- Situação
  - Aluno de graduação
  - Aluno de pós-graduação
  - Acadêmicos em geral (e.g. professor)
  - Profissional desenvolvedor de software (principalmente ou não)
  - Desenvolvedor hobbysta

**Comment by abelsiqueira** [comment]
cc @haltsimog

**Comment by almeidaraul** [comment]
https://goo.gl/forms/J62F29jMm5Gpl85m2 Esse aqui tá legal? Adicionei umas perguntas de curso/universidade por questão de observar o alcance.

**Comment by abelsiqueira** [comment]
Eu mudaria as duas questões pra serem um pouco mais abrangentes. Dá pra fazer condicional na inscrição, de acordo com a seleção feita ali.

Se aluno
- Qual instituição
- Qual curso
Se academico
- Qual instituição
Se profissional
- Qual empresa

Sobre o git, eu mudaria a última e adicionaria
- Sim, e sei usar o básico (commit, log, status, add)
- Sim, e sei mais que o básico (rebase, reset, add -p)

**Comment by almeidaraul** [comment]
Alterações feitas.

**Comment by abelsiqueira** [comment]
Fantástico. Vou adicionar no site e considerar aberta as inscrições.
